#!/bin/bash

# Install native apps

brew install caskroom/cask/brew-cask
brew tap caskroom/versions

brew install --cask google-chrome
brew install --cask spectacle
brew install --cask flycut
brew install --cask slack
brew install --cask charles

for f in ~/.*; do
  if [[ $f == */.Caskfile.*local ]]; then
    printf "Updating local packages from ${f}...\n"
    $f
  fi
done
