#!/bin/bash

run_help() {

cat <<EOT
Usage: $(basename "$0") [options]

Options:
    -h, --help        Print this help text
    --no-installs     Suppress application and package updates
    --no-applications Suppress application updates
    --no-packages     Suppress package updates
    --no-sync         Suppress pulling from the remote repository
    --no-brew         Skip all steps involving brew (useful for servers where you cant install brew)

EOT

}
